// Builds the single-file `yacwu` executable.
//
// Run via `bun run build:bin`, which first produces the SvelteKit build (`vite
// build`, using svelte-adapter-bun) and then invokes this script. We walk the
// generated client assets, emit a module that embeds each one into the binary
// (`import ... with { type: 'file' }`), and compile binary-entry.js with
// `bun build --compile`.
import { readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { $ } from 'bun';

const root = import.meta.dir; // scripts/
const buildDir = join(root, '..', 'build');

if (!existsSync(join(buildDir, 'handler.js'))) {
	console.error('build/ not found — run `vite build` first.');
	process.exit(1);
}

function walk(dir: string): string[] {
	const out: string[] = [];
	for (const name of readdirSync(dir)) {
		const p = join(dir, name);
		if (statSync(p).isDirectory()) out.push(...walk(p));
		else out.push(p);
	}
	return out;
}

// Map every client asset (and any prerendered files) to its URL path.
const sources = [join(buildDir, 'client'), join(buildDir, 'prerendered')].filter(existsSync);

const imports: string[] = [];
const entries: string[] = [];
let i = 0;
for (const dir of sources) {
	for (const file of walk(dir)) {
		const urlPath = '/' + relative(dir, file).split(sep).join('/');
		const importPath = './' + relative(root, file).split(sep).join('/');
		const name = `a${i++}`;
		imports.push(`import ${name} from ${JSON.stringify(importPath)} with { type: 'file' };`);
		entries.push(`\t[${JSON.stringify(urlPath)}, ${name}]`);
	}
}

const generated = `// AUTO-GENERATED by scripts/build-binary.ts — do not edit.
${imports.join('\n')}

export const ASSETS = new Map([
${entries.join(',\n')}
]);
`;
writeFileSync(join(root, '.gen-assets.js'), generated);
console.log(`embedding ${i} static asset(s)`);

const out = join(root, '..', 'yacwu');
await $`bun build --compile --minify ${join(root, 'binary-entry.js')} --outfile ${out}`;
console.log(`built ${out}`);
